# Generated by Django 3.0 on 2025-10-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_data_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
